server:
 address: 192.168.1.100
spring:
 profiles: development
server:
 address: 127.0.0.1
spring:
 profiles: production
server:
 address: 192.168.1.120
my:
 servers:
  - dev.example.com
  - another.example.com